### ISSUE TITLE
Nodes center to gridline and not the center of cell

### ISSUE THREAD

**Issue by torbgy** [iVis-at-Bilkent/cytoscape.js-grid-guide#36]
Hi!

Is it possible to snap nodes to the gridline? like that the node is snapped to the cross of the gridline instead of the center of the cell?

**Comment by kinimesi** [comment]
No, this is not possible. In the current implementation, the dragged node positioned in the center of the closest grid (cell).

**Comment by gregroyal** [comment]
is this possible to get worked? whats the technical limitations?

**Comment by kinimesi** [comment]
It could be as simple as not adding `0.5` factor when the snap position is calculated:

https://github.com/iVis-at-Bilkent/cytoscape.js-grid-guide/blob/9649d89aafd702b097456adccdcf0395a818907d/src/snap_on_release.js#L18

Test this and see if it has the effect you want (after modifying this line, snap during drag should snap to grid line as well).

This needs to be optional, so that one can switch between the original behavior and the new one. An option named `snapToGridCenter` can be defined (the default value should be `true`).

You can do a PR if you like.

**Comment by gregroyal** [comment]
Created PR https://github.com/iVis-at-Bilkent/cytoscape.js-grid-guide/pull/38 to address this with your implementation suggestion. It worked like a charm!

**Comment by kinimesi** [comment]
@torbgy this feature is now implemented. You can pull it from unstable branch.

**Comment by gregroyal** [comment]
Hows the release coming? I'm still using this featured as a one-off. Any updates on the next release?
