### ISSUE TITLE
Guidelines messed up when window resized

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-grid-guide#9]
To reproduce (on Windows 10 with latest Chrome):
- Start ChiSE with a full screen window,
- Then resize the window to be smaller. Now the guidelines seem to be messed up (displayed in incorrect locations).

**Comment by mrsfy** [comment]
![guidelines_bug](https://cloud.githubusercontent.com/assets/13938178/16989005/15588fd6-4e9b-11e6-9445-0d5dcf917d9d.png)
The crosspoint of guidelines shows the renderedPosition of compound. Also I couldn't reproduce it in demo.html of grid-guide. Thus, this issue is probably caused by sbgn spesific edits on cytoscape.js

**Comment by ugurdogrusoz** [comment]
See https://github.com/iVis-at-Bilkent/chise.js/issues/32

**Comment by metincansiper** [comment]
I reproduced such errors in 'demo.html'. Therefore, I think that this problem may not be special to ChiSE. Some related screenshots are below:

![grid-guide-error](https://cloud.githubusercontent.com/assets/6534865/17665212/24899fa6-6302-11e6-8208-cdc655f6810c.png)

![grid-guide-error2](https://cloud.githubusercontent.com/assets/6534865/17665213/2bb54a0a-6302-11e6-8ff8-8bfcffcf129e.png)

**Comment by mrsfy** [comment]
It is not a problem. As Kramer is not a child of the parent node, it draws a guideline to center of parent node.

**Comment by ugurdogrusoz** [comment]
Yes, looks like guidelines in these examples are fine.
